### ISSUE TITLE
Win10-64 does not execute

### ISSUE THREAD

**Issue by worekarolis** [hdonk/eora3D#9]
Wont launch on windows 10. Unfortunately I'm not a programmer and can't tell why its not working.

Attaching error log.

[hs_err_pid33588.log](https://github.com/hdonk/eora3D/files/6901896/hs_err_pid33588.log)

**Comment by hdonk** [comment]
Hi,
   When does this happen? Do you have a Bluetooth Low Energy interface in
your PC?
Cheers,
Nick

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by worekarolis** [comment]
It happens when running a .bat file. Yes, I have Bluetooth LE Generic
Attribute Service.

X:\Downloads\eora3d_java>java -Djava.library.path=dlls;C:\WINDOWS\system32
-jar eora3D.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at
org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.UnsatisfiedLinkError:
X:\Downloads\eora3d_java\dlls\libglesv2.dll: Can't load AMD 64-bit .dll on
a IA 32-bit platform
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at eora3D.Eora3D_MainWindow.<init>(Eora3D_MainWindow.java:94)
        at eora3D.eora3D.main(eora3D.java:24)

**Comment by worekarolis** [comment]
shoot sorry, just realised that I have 32bit java
